### ISSUE TITLE
Line numbers at word wrapping

### ISSUE THREAD

**Issue by aplsimple** [thanoulis/tedit#1]
At word wrapping, if a long line is wrapped, its line number may be shown incorrectly, i.e. not in the line start:

![tedit1](https://user-images.githubusercontent.com/37333988/104085548-831db680-5261-11eb-9f9d-652d1e93d8f5.png)

This could be fixed with the following change of **lineNumbers** proc:

   `set i [$text index "$i +1 lines linestart"]`

instead of

   `set i [$text index "$i +1 lines"]`

...as seen below:

![tedit2](https://user-images.githubusercontent.com/37333988/104085554-903aa580-5261-11eb-9074-0c5e13c6b286.png)

Thank you a lot.

Regards,
Alex

**Comment by thanoulis** [comment]
It is now fixed in [1.7.8](https://github.com/thanoulis/tedit/releases/tag/v1.7.8).
Thanks a lot Alex!
